# backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubescriptor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubescriptor-backend
  template:
    metadata:
      labels:
        app: kubescriptor-backend
    spec:
      containers:
      - name: kubescriptor-backend
        image: your-docker-username/kubescriptor-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubescriptor-backend
spec:
  selector:
    app: kubescriptor-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
